sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t keldstehr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true keldstehr/docker-react npm run test