sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t keldstehr/docker-react -f Dockerfile.dev .

script:
  - docker run keldstehr/docker-react npm run test -- --coverage